import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WishlistProvider } from "@/Context/wishlist";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "@/Context/cart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dvago.com",
  description: "Generated by Raheel Shaikh",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <CartProvider>
            <WishlistProvider>
              <main>
                {children}
                <Toaster
                  position="top-right"
                  toastOptions={{
                    duration: 3000,
                    style: {
                      background: "#fff",
                      color: "#333",
                      border: "1px solid #8DC63F",
                    },
                  }}
                />
              </main>
            </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}